theme: jekyll-theme-tactile
title: dotPcnova | Pcnova's software development blog
description: A space for sharing programming and technical knowledge.

plugins:
  - jemoji

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true