theme: jekyll-theme-tactile
title: Welcome to pcnova's blog!
description: A space for sharing programming and other technical knowledge.

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
